name: products_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc:
  dio:
  flutter_native_splash: ^2.4.6

flutter_native_splash:
  color: "#e91e63"
  image: assets/images/logo.png
  android: true
  android_12:
    color: "#e91e63"
    image: assets/images/logo_12.png

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
